trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.x'
    packageType: 'sdk'

- checkout: self
  persistCredentials: true

- script: |
    echo "Fetching Git History..."
    git log > git-history.txt
  displayName: 'Document Git History'

- script: |
    echo "Building project..."
    dotnet build
  displayName: 'Build .NET Core Project'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'git-history.txt'
    ArtifactName: 'GitHistory'
    publishLocation: 'container'
