# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    packageType: sdk
    version: '3.1.x' # Replace with your required version

- task: DotNetCoreCLI@2
  displayName: 'Build Project'
  inputs:
    command: build
    projects: '**/*.csproj' # Replace with the correct pattern to match your project files
    arguments: '--configuration Release' # Optional arguments

- script: docfx build $(Build.SourcesDirectory)/docfx.json
  displayName: 'Generate Documentation'

